import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import {mkdtemp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {CatalogService, validateAdapter} from '../src/catalog.mjs';
import {ArtifactStore} from '../src/artifacts.mjs';
import {ExecutionMaterializer} from '../src/materializer.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const evidenceSha256 = 'a'.repeat(64);

function generatedAdapter() {
  return {
    adapter_version: '1.0',
    adapter_id: 'clock.open',
    app_id: 'clock',
    function: 'open',
    risk: 'local_state',
    requires: {vision: true},
    arguments_schema: {type:'object', additionalProperties:false, required:[], properties:{}},
    operations: [
      {op: 'deck_confirm'},
      {op: 'app_start', app_name: 'Clock', args: ''},
      {op: 'capture_vision'},
      {op: 'expect', expectation: 'Clock application is visible'},
    ],
    test_plan: ['Approve the exact adapter hash, open Clock, and verify the display before promotion.'],
  };
}

function autonomousAdapter() {
  return {
    adapter_version: '1.0',
    adapter_id: 'clock.open.auto',
    app_id: 'clock',
    function: 'open_auto',
    risk: 'local_state',
    arguments_schema: {type:'object', additionalProperties:false, required:[], properties:{}},
    operations: [
      {op: 'app_start', app_name: 'Clock', args: ''},
      {op: 'wait_ms', ms: 100},
      {op: 'app_exit'},
    ],
    test_plan: ['Open and close Clock on the connected Flipper and require correlated before/after proof.'],
  };
}

test('generated adapters remain non-executable until operator evidence promotes their exact hash', async () => {
  const stateDir = await mkdtemp(path.join(os.tmpdir(), 's1r3n-catalog-'));
  const catalog = new CatalogService({packageRoot: root, stateDir});
  const artifacts = new ArtifactStore({packageRoot: root, stateDir});
  await Promise.all([catalog.load(), artifacts.load()]);

  const staged = await artifacts.verifyAndStage({type: 'adapter', value: generatedAdapter()}, 'official_and_pinned');
  await catalog.registerGeneratedAdapter('clock', 'open', staged);
  const pending = await catalog.getAdapter('clock.open');
  assert.equal(pending.verification_status, 'staged_pending_review');

  const job = {
    target: 'flipper-link', job_id: 'r:0', step_id: 'open-clock', adapter_id: 'clock.open',
    operation: 'adapter', risk: 'local_state', approval: 'operator', requires_approval: true,
    timeout_ms: 5000, arguments: {},
  };
  const disabled = new ExecutionMaterializer({catalog, artifacts, policy:{allowGeneratedAdapterExecution:false, requireVisionForGeneratedAdapters:true}});
  await assert.rejects(() => disabled.materialize(job), /not approved for execution|generated adapter execution disabled/);

  await catalog.promoteGeneratedAdapter({adapterId: 'clock.open', operatorId: 'operator-1', testEvidenceSha256: evidenceSha256});
  const enabled = new ExecutionMaterializer({catalog, artifacts, policy:{allowGeneratedAdapterExecution:true, requireVisionForGeneratedAdapters:true}});
  const materialized = await enabled.materialize(job);
  assert.equal(materialized.flipper_program.adapter.verification_status, 'operator_verified');
  assert.equal(materialized.route.physical_owner, 's3-cam');
  assert.match(materialized.flipper_program.sha256, /^[a-f0-9]{64}$/);
  assert.equal(materialized.flipper_program.operations[0].op, 'deck_confirm');
});

test('machine-verified low-risk adapter is autonomous after closed-loop verification', async () => {
  const stateDir = await mkdtemp(path.join(os.tmpdir(), 's1r3n-auto-catalog-'));
  const catalog = new CatalogService({packageRoot: root, stateDir});
  const artifacts = new ArtifactStore({packageRoot: root, stateDir});
  await Promise.all([catalog.load(), artifacts.load()]);

  const staged = await artifacts.verifyAndStage({type:'adapter', value:autonomousAdapter()}, 'local_only');
  await catalog.registerAutoGeneratedAdapter('clock', 'open_auto', staged);
  const adapter = await catalog.getAdapter('clock.open.auto');
  assert.equal(adapter.verification_status, 'machine_verified');
  assert.equal(adapter.autonomous_safe, true);

  const materializer = new ExecutionMaterializer({catalog, artifacts, policy:{allowGeneratedAdapterExecution:true, requireVisionForGeneratedAdapters:true}});
  const job = {
    target:'flipper-link', job_id:'auto:0', step_id:'open-clock-auto', adapter_id:'clock.open.auto', operation:'adapter',
    risk:'local_state', approval:'auto', requires_approval:false, timeout_ms:5000, arguments:{},
  };
  const materialized = await materializer.materialize(job);
  assert.equal(materialized.flipper_program.adapter.verification_status, 'machine_verified');
  assert.equal(materialized.flipper_program.approval, 'auto');
  assert.equal(materialized.route.physical_owner, 's3-cam');
});

test('adapter validator rejects raw commands and incomplete transmit adapters', () => {
  const base = generatedAdapter();
  assert.throws(
    () => validateAdapter({...base, operations:[{op:'app_start', app_name:'Clock', args:'', command:'raw'}]}),
    /unexpected field|field denied/,
  );
  assert.throws(
    () => validateAdapter({...base, adapter_id:'ir.tx', app_id:'infrared', function:'transmit', risk:'transmit'}),
    /frequency profile/,
  );
});
