[platformio]
default_envs = s3-cam
src_dir = src

[env:s3-cam]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.psram_type = opi
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DM3RMA1D_S3_CAM_BUILD=1
