[platformio]
default_envs = core-s3
src_dir = src

[env:core-s3]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.psram_type = opi
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
