[platformio]
default_envs = vision-s3

[env:vision-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D M3RMA1D_VISION_BUILD=1
